name: CI Testing Demo

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout code'
        uses: 'actions/checkout@v5'
      - name: 'Run building script'
        run: echo "Running the build script ..... "
      - name: 'Run Test'
        run: echo "Running Test cases ....... "

